name = "BayesNetExplorer"
uuid = "dca4ed0a-a93c-4845-9996-6581d99b4116"
authors = ["Scott Watkins and Javier Hernandez"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
